### ISSUE TITLE
Release 2.0.1 Errors with Kodi 19

### ISSUE THREAD

**Issue by bobhavlin** [XBMC-Addons/plugin.library.node.editor#16]
Downgraded to 2.0.0 and error went away.
`
Logfile on windows shows:
2021-03-04 16:27:34.045 T:32208   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.library.node.editor/?ltype=video
2021-03-04 16:27:34.065 T:28484   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.library.node.editor/?ltype=video) failed
2021-03-04 16:27:35.700 T:28484    INFO <general>: Loading skin file: SkinSettings.xml, load type: LOAD_EVERY_TIME
2021-03-04 16:27:41.361 T:28484   ERROR <general>: Control 55 in window 10001 has been asked to focus, but it can't
2021-03-04 16:27:41.393 T:19272    INFO <general>: initializing python engine.
2021-03-04 16:27:41.473 T:19272   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'xmbcvfs'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.library.node.editor\plugin.py", line 2, in <module>
                                                       from resources.lib import addon
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.library.node.editor\resources\lib\addon.py", line 4, in <module>
                                                       from resources.lib.common import *
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.library.node.editor\resources\lib\common.py", line 4, in <module>
                                                       import xbmc, xmbcvfs, xbmcaddon
                                                   ModuleNotFoundError: No module named 'xmbcvfs'
                                                   -->End of Python script error report<--

2021-03-04 16:27:41.493 T:19272    INFO <general>: Python interpreter stopped

**Comment by enen92** [comment]
Thanks much for the info, I'll fix this asap

**Comment by enen92** [comment]
Fixed in https://github.com/XBMC-Addons/plugin.library.node.editor/commit/19edbebd80589463e448408dc72ba3964107d7e8

**Comment by enen92** [comment]
Already in the repo: https://github.com/xbmc/repo-plugins/pull/3441
