### ISSUE TITLE
Unable to add a custom value for Music library node

### ISSUE THREAD

**Issue by Shredder5262** [XBMC-Addons/plugin.library.node.editor#60]
I am trying to add a custom property for soundtracks (similar to complications) where if soundtrack = true then the album is displayed within the node. When i try to add the custom property of 'soundtrack' I get an error that displays in this log. 

`2023-11-23 11:21:48.305 T:2456    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "D:\Kodi V20\Kodi V20.2\portable_data\addons\plugin.library.node.editor\plugin.py", line 6, in <module>
                                                       addon.run(sys.argv)
                                                     File "D:\Kodi V20\Kodi V20.2\portable_data\addons\plugin.library.node.editor\resources\lib\addon.py", line 834, in run
                                                       Main(params, ltype, RULE, ATTRIB, PATHRULE, ORDERBY)
                                                     File "D:\Kodi V20\Kodi V20.2\portable_data\addons\plugin.library.node.editor\resources\lib\addon.py", line 254, in __init__
                                                       self.PATHRULE.editMatch( self.PARAMS[ "actionPath" ], int( self.PARAMS[ "rule" ] ) )
                                                     File "D:\Kodi V20\Kodi V20.2\portable_data\addons\plugin.library.node.editor\resources\lib\pathrules.py", line 194, in editMatch
                                                       self.manuallyEditMatch( actionPath, ruleNum, splitPath[ ruleNum ][ 0 ], currentValue )
                                                     File "D:\Kodi V20\Kodi V20.2\portable_data\addons\plugin.library.node.editor\resources\lib\pathrules.py", line 203, in manuallyEditMatch
                                                       self.ATTRIB.writeUpdatedPath( actionPath, ( ruleNum, returnVal.decode( "utf-8" ), currentValue ) )
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--`

**Comment by Shredder5262** [comment]
Is this repo being monitored/ supported anymore?
